services:
  web:
    image: npsat:latest
    ports:
      - "3000:3000"
    volumes:
     - .:/app
     - ./node_modules:/app/node_modules
     - /app/.next
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: npm start